[package]
name = "species"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
web-sys = { version = "0.3.70", features = ["console"] }
serde_json = "1.0.128"
once_cell = "1.20.1"
